/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_halzhang_android_example_jniexample_JNIEngine */

#ifndef _Included_com_halzhang_android_example_jniexample_JNIEngine
#define _Included_com_halzhang_android_example_jniexample_JNIEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_halzhang_android_example_jniexample_JNIEngine
 * Method:    init
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_halzhang_android_example_jniexample_JNIEngine_init
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
